<?php
	$ADMIN_AR_ARR=array(
		array("menu"=>"pack","title"=>"Memberships","cmd"=>array("pack","packedit")),
		array("menu"=>"user","title"=>"Members","cmd"=>array("user","useredit","ipn","ipn1")),
		array("menu"=>"bg","title"=>"Graphics / License Generators","cmd"=>array("bg","bgedit","lgbg","lgt")),
		array("menu"=>"pr","title"=>"Products","cmd"=>array("pr","predit")),
		array("menu"=>"prb","title"=>"CB Products","cmd"=>array("prb","prbedit","tpl","tpledit")),
		array("menu"=>"page","title"=>"Pages","cmd"=>array("pagef","pagefedit","page","pageedit")),
		array("menu"=>"art","title"=>"Articles","cmd"=>array("art","artedit")),
		array("menu"=>"bonus","title"=>"Bonuses","cmd"=>array("bonus","bonusedit")),
		array("menu"=>"door","title"=>"Doorways","cmd"=>array("door","dooredit")),
		array("menu"=>"ad","title"=>"Ads","cmd"=>array("ad","adedit")),
		array("menu"=>"poll","title"=>"Polls","cmd"=>array("poll","polledit","pollview")),
		array("menu"=>"setup","title"=>"Settings","cmd"=>array("setup","menu","mes","mesedit","email","backup","theme"))
	);

	$ADMIN_CMD=array(
		"login"=>array("Authorization"),
		"home"=>array("Dashboard","home"),
		"info"=>array("Profile","info"),
		"admin"=>array("Admin Members","admin"),
		"adminedit"=>array(($_GET["id"]?"Edit":"Add New")." Admin Member",($_GET["id"]?"admin":"adminedit")),
		"pack"=>array("Memberships","pack"),
		"packedit"=>array(($_GET["id"]?"Edit":"Add New")." Membership",($_GET["id"]?"pack":"packedit")),
		"user"=>array("Members","user"),
		"useredit"=>array(($_GET["id"]?"Edit":"Add New")." Member",($_GET["id"]?"user":"useredit")),
		"ipn"=>array("IPN Requests","ipn"),
		"ipn1"=>array("IPN SUM","ipn"),
		"bg"=>array("Graphics Generator Premium Templates","bg"),
		"bgedit"=>array(($_GET["id"]?"Edit":"Add New")." GG Premium Template","bg"),
		"lgbg"=>array("License Generator Backgrounds","lgbg"),
		"lgt"=>array("License Generator Terms","lgt"),
		"pr"=>array("Products","pr"),
		"prb"=>array("CB Products","prb"),
		"prbedit"=>array(($_GET["id"]?"Edit":"Add New")." CB Product","prb"),
		"tpl"=>array("CB Templates","tpl"),
		"tpledit"=>array(($_GET["id"]?"Edit":"Add New")." CB Template","tpl"),
		"pagef"=>array("Front End Pages","pagef"),
		"pagefedit"=>array(($_GET["id"]?"Edit":"Add New")." Front End Page",($_GET["id"]?"pagef":"pagefedit")),
		"page"=>array("Member Pages","page"),
		"pageedit"=>array(($_GET["id"]?"Edit":"Add New")." Member Page",($_GET["id"]?"page":"pageedit")),
		"art"=>array("Articles","art"),
		"artedit"=>array(($_GET["id"]?"Edit":"Add New")." Article",($_GET["id"]?"art":"artedit")),
		"bonus"=>array("Bonuses","bonus"),
		"bonusedit"=>array(($_GET["id"]?"Edit":"Add New")." Bonus",($_GET["id"]?"bonus":"bonusedit")),
		"door"=>array("Doorways","door"),
		"dooredit"=>array(($_GET["id"]?"Edit":"Add New")." Doorway",($_GET["id"]?"door":"dooredit")),
		"ad"=>array("Ads","ad"),
		"adedit"=>array(($_GET["id"]?"Edit":"Add New")." Ad",($_GET["id"]?"ad":"adedit")),
		"poll"=>array("Polls","poll"),
		"polledit"=>array(($_GET["id"]?"Edit":"Add New")." Poll",($_GET["id"]?"poll":"polledit")),
		"pollview"=>array("Poll Results","poll"),
		"setup"=>array("General Settings","setup"),
		"menu"=>array("Member CP Menu","menu"),
		"mes"=>array("Member CP Notifications","mes"),
		"mesedit"=>array(($_GET["id"]?"Edit":"Add New")." Notification","mes"),
		"email"=>array("Email Responders","email"),
		"backup"=>array("Backup","backup"),
		"theme"=>array("Theme","theme")
	);

	$ADMIN_MENU=array(
		"home"=>array("Dashboard",array("home"=>"Home","info"=>"Edit Profile")),
		"admin"=>array("Admin Members",array("admin"=>"All Admin Members","adminedit"=>"Add New")),
		"pack"=>array("Memberships",array("pack"=>"All Memberships","packedit"=>"Add New")),
		"user"=>array("Members",array("user"=>"All Members","useredit"=>"Add New","ipn"=>"IPN Requests")),
		"bg"=>array("Generators",array("bg"=>"GG Premium Temlates","lgbg"=>"LG Backgrounds","lgt"=>"LG Terms")),
		"pr"=>array("Products",array("pr"=>"Products")),
		"prb"=>array("Commission Builder",array("prb"=>"CB Products","tpl"=>"CB Templates")),
		"page"=>array("Pages",array("pagef"=>"Front End Pages","pagefedit"=>"Add New Front End Page","page"=>"Member Pages","pageedit"=>"Add New Member Page")),
		"art"=>array("Articles",array("art"=>"All Articles","artedit"=>"Add New")),
		"bonus"=>array("Bonuses",array("bonus"=>"All Bonuses","bonusedit"=>"Add New")),
		"door"=>array("Doorways",array("door"=>"All Doorways","dooredit"=>"Add New")),
		"ad"=>array("Ads",array("ad"=>"All Ads","adedit"=>"Add New")),
		"poll"=>array("Polls",array("poll"=>"All Polls","polledit"=>"Add New")),
		"setup"=>array("Settings",array("setup"=>"General","menu"=>"Member CP Menu","mes"=>"Member CP Notifications","email"=>"Email Responders","backup"=>"Backup","theme" => "Theme"))
	);

	$USER_CMD=array(
		"login"=>array("Authorization",""),
		"forgot"=>array("Forgot Password",""),
		"subdomain"=>array("Sub Domain",""),
		"download"=>array("Download Zip",""),
		"door"=>array("Dashboard",""),
		"home"=>array("Dashboard","home"),
		"mes"=>array("Notifications",""),
		"mesview"=>array("View Notification",""),
		"info"=>array("My Profile","info"),
		"renew"=>array("Upgrade Membership","renew"),
		"deny"=>array("Access Denied","info"),
		"autoresponder"=>array("Integrations","autoresponder"),
		"pageb"=>array("Done for You","pageb"),
		"pagebedit"=>array(($_GET["id"]?"Edit":"Add New")." Done for You Campaign","pageb"),
		"pageb2"=>array("Done for You 2","pageb2"),
		"pagebedit2"=>array(($_GET["id"]?"Edit":"Add New")." Done for You 2 campaign","pageb2"),
		"veswipe"=>array("View``````` Email Swipe","eswipes"),
		"cbpredit"=>array("CB Product Edit","eswipes"),
		"cbt"=>array("Auto Profit Boost","cbt"),
		"cbtedit"=>array("Auto Profit Boost","cbtedit"),
		"exp"=>array("Auto Profit Boost","exp"),
		"expedit"=>array("Auto Profit Boost","expedit"),
		"scp"=>array("Auto Profit Boost","scp"),
		"bba"=>array("Your Campaigns","bba"),
		"bbaedit"=>array(($_GET["id"]?"Edit":"Create")." New Campaign","bba"),
		"bba2"=>array("Super Affiliate Builder","bba2"),
		"bbaedit2"=>array(($_GET["id"]?"Edit":"Create")." Super Affiliate Builder","bba2"),
		"cover"=>array("Graphics Generator","cover"),
		"aie"=>array("Create Flat Graphics","cover"),
		"cover3d"=>array("Create 3D Graphics","cover"),
		"coverok"=>array("Create Graphics","cover"),
		"lg"=>array("License Generator","lg"),
		"lgedit"=>array(($_GET["id"]?"Edit":"Add New")." License Certificate","lg"),
		"lgt"=>array("Custom License Terms","lg"),
		"art"=>array("Articles","art"),
		"artview"=>array("View Article","art"),
		"bonus"=>array("Bonuses","bonus"),
		"bonusview"=>array("View Bonus","bonus"),
		"page"=>array("%sitename%",""),
		"tag"=>array("%sitename%",""),
		"prview"=>array("Download Product",""),
		"social"=>array("Social Accounts","social"),
		"socialedit"=>array(($_GET["id"]?"Edit":"Add")." another social account","social"),
		"socialshare"=>array("Social Share","socialshare"),
		"otodfy"=>array("OTO Done For You","otodfy"),
		"otodfyedit"=>array(($_GET["id"]?"Edit":"Create") . " otodfy","otodfyedit"),
		"campaigns"=>array("Campaigns","campaigns"),
		"campaignsedit"=>array(($_GET["id"]?"Edit":"Create") . " campaign","campaignsedit"),
		"campaignstyle"=>array("Style","campaignstyle"),
		"campaignsdfy"=>array("Done For You","campaignsdfy"),
		"campaignsdfyedit"=>array(($_GET["id"]?"Edit":"Create") . " campaign","campaignsdfyedit"),
		"campaignsdfy2"=>array("Done For You Bonus","campaignsdfy2"),
		"campaignsdfy2edit"=>array(($_GET["id"]?"Edit":"Create") . " campaign","campaignsdfy2edit"),
		"pages"=>array("Pages","pages"),
		"pagesedit"=>array(($_GET["id"]?"Edit":"Create") . " page","pagesedit"),
		"affiliatelinks"=>array("Resource Slider","affiliatelinks"),
		"affiliatelinksedit"=>array(($_GET["id"]?"Edit":"Create") . " resource slider","affiliatelinksedit"),
		"affiliatelinkscollection"=>array("Resource Slider: Collection","affiliatelinkscollection"),
		"affiliatelinkscollectionedit"=>array(($_GET["id"]?"Edit":"Create") . " resource slider collection","affiliatelinkscollectionedit"),
		"campaign1"=>array("Campaigns1","campaign1"),
		"category"=>array("Category","category"),
		"categoryedit"=>array(($_GET["id"]?"Edit":"Create") . " category","categoryedit"),
		"ads2"=>array("Ads","ads2"),
		"ads2edit"=>array(($_GET["id"]?"Edit":"Ads") . " ads2","ads2edit"),
		"menus"=>array("Menus","menus"),
		"menusedit"=>array(($_GET["id"]?"Edit":"Menu") . " menus","menusedit"),
		"contents"=>array("Contents","contents"),
		"content"=>array("Content","content"),
		"contentedit"=>array(($_GET["id"]?"Edit":"Content") . " content","contentedit"),
		"popup"=>array("Popup","popup"),
		"popupedit"=>array(($_GET["id"]?"Edit":"Popup") . " popup","popupedit"),
		"ping"=>array("Ping","ping"),
		"subdomains"=>array("Subdomains","subdomains")
	);

	$USER_MENU=array(
		"home"=>array("Dashboard","pe-7s-home"),
		"info"=>array("My Profile","pe-7s-user"),
		"autoresponder"=>array("Integrations","pe-7s-gift"),
		"pageb"=>array("Done for You","pe-7s-gift"),
		"pageb2"=>array("Done for You 2","pe-7s-gift"),
		"cbt"=>array("DFY Funnels Tools","pe-7s-paper-plane"),
		"bba"=>array("Your Campaigns","pe-7s-gift"),
		"bba2"=>array("Super Affiliate","pe-7s-gift"),
		"social"=>array("Social","fa fa-twitter"),
		"socialshare"=>array("Social","fa fa-twitter"),
		"otodfy"=>array("OTO Done For You","fas fa-bullhorn"),
		"campaigns"=>array("Campaigns","fas fa-bullhorn"),
		"campaignsdfy"=>array("Done For You","fa fa-flag"),
		"campaignsdfy2"=>array("Done For You Bonus","fa fa-flag"),
		"pages"=>array("Pages","fa fa-book"),
		"affiliatelinks"=>array("Resource Slider","fa fa-link"),
		"campaign1"=>array("Campaign1","fa fa-flag"),
		"category"=>array("Category","fa fa-flag"),
		"ads2"=>array("Ads","fa fa-flag"),
		"menus"=>array("Menus","fa fa-flag"),
		"contents"=>array("Contents","fa fa-flag"),
		"content"=>array("Content","fa fa-flag"),
		"popup"=>array("Popup","fa fa-flag"),
		"ping"=>array("Ping","fab fa-safari"),
		"subdomains"=>array("Subdomains","fab fa-safari"),
	);

?>